background: center / cover no-repeat fixed  url('/local/lovelace/bg_long.png?v=1')
kiosk_mode:
  mobile_settings:
    hide_header: true
views:
  - icon: 'mdi:shield-home'
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: 'custom:button-card'
            size: 25px
            icon: 'mdi:close'
            tap_action:
              action: navigate
              navigation_path: /lovelace/0
            styles:
              card:
                - width: 40px
                - height: 40px
                - background-color: 'rgba(255,255,255,0)'
                - box-shadow: none
                - margin-bottom: 15px
              icon:
                - margin-left: px
          - type: markdown
            content: '### Security'
            card_mod:
              style: |
                ha-card {
                  background: rgba(0,0,0,0);
                  box-shadow: none;
                  padding: 0px;
                  margin-bottom: -35px;
                  top: -20px;
                  left: 5px;
                }
          - type: 'custom:mod-card'
            card_mod:
              style: |
                ha-card {
                  width: 92%;
                  margin: auto;
                }
            card:
              type: horizontal-stack
              cards:
                - type: 'custom:button-card'
                  entity: alarm_control_panel.abode_alarm
                  name: Alarm
                  icon: 'mdi:shield-home-outline'
                  show_state: true
                  aspect_ratio: 1/1
                  card_size: 3
                  size: 30%
                  tap_action:
                    action: call-service
                    service: |
                      [[[
                        if (states['alarm_control_panel.abode_alarm'].state == "disarmed")
                          return "alarm_control_panel.alarm_arm_home";
                        return "alarm_control_panel.alarm_disarm";
                      ]]]
                    service_data:
                      entity_id: alarm_control_panel.abode_alarm
                      code: 1914
                  hold_action:
                    action: call-service
                    service: |
                      [[[
                        if (states['alarm_control_panel.abode_alarm'].state == "disarmed")
                          return "alarm_control_panel.alarm_arm_away";
                        return "alarm_control_panel.alarm_disarm";
                      ]]]
                    service_data:
                      entity_id: alarm_control_panel.abode_alarm
                      code: XXXX
                  styles:
                    icon:
                      - left: 15px
                      - top: '-25px'
                      - color: |
                          [[[
                            if (states['alarm_control_panel.abode_alarm'].state == "disarmed")
                              return "rgba(24, 199, 71,1)";
                            return "rgba(230, 0, 0,0.7)";
                          ]]]
                    card:
                      - background: |
                          [[[
                            if (states['alarm_control_panel.abode_alarm'].state == "disarmed") 
                              return "rgba(255,255,255,0.1)";
                            return "rgba(255,255,255,0.7)";
                          ]]]
                      - border-radius: 12px
                      - box-shadow: 5px 5px 5px;
                      - font-size: 100%
                    grid:
                      - grid-template-areas: '"i" "n" "s"'
                      - grid-template-columns: 1fr
                      - grid-template-rows: 1fr min-content min-content
                    img_cell:
                      - align-self: start
                      - text-align: start
                    name:
                      - justify-self: start
                      - padding-left: 10px
                      - margin-top: '-65px'
                      - color: |
                          [[[
                            if (states['alarm_control_panel.abode_alarm'].state == "disarmed")
                              return "white";
                            return "black";
                          ]]]
                    state:
                      - justify-self: start
                      - padding-left: 10px
                      - margin-top: '-32px'
                      - color: |
                          [[[
                            if (states['alarm_control_panel.abode_alarm'].state == "disarmed")
                              return "white";
                            return "black";
                          ]]]
                - type: 'custom:button-card'
                  entity: lock.front_door_lock
                  name: Front Door
                  show_state: true
                  aspect_ratio: 1/1
                  card_size: 3
                  size: 25%
                  tap_action:
                    action: call-service
                    service: |
                      [[[
                        if (states['lock.front_door_lock'].state == "locked")
                          return "lock.unlock";
                        return "lock.lock";
                      ]]]
                    service_data:
                      entity_id: lock.front_door_lock
                  styles:
                    icon:
                      - left: 15px
                      - top: '-25px'
                      - color: |
                          [[[
                            if (states['lock.front_door_lock'].state == "unlocked")
                              return "rgba(230, 0, 0,0.7)";
                            return "white";
                          ]]]
                    card:
                      - background: |
                          [[[
                            if (states['lock.front_door_lock'].state == "locked") 
                              return "rgba(255,255,255,0.1)";
                            return "rgba(255,255,255,0.7)";
                          ]]]
                      - border-radius: 12px
                      - box-shadow: 5px 5px 5px;
                      - font-size: 100%
                    grid:
                      - grid-template-areas: '"i" "n" "s"'
                      - grid-template-columns: 1fr
                      - grid-template-rows: 1fr min-content min-content
                    img_cell:
                      - align-self: start
                      - text-align: start
                    name:
                      - justify-self: start
                      - padding-left: 10px
                      - margin-top: '-65px'
                      - color: |
                          [[[
                            if (states['lock.front_door_lock'].state == "unlocked")
                              return "black";
                            return "white";
                          ]]]
                    state:
                      - justify-self: start
                      - padding-left: 10px
                      - margin-top: '-32px'
                      - color: |
                          [[[
                            if (states['lock.front_door_lock'].state == "unlocked")
                              return "black";
                            return "white";
                          ]]]
                - type: 'custom:button-card'
                  entity: lock.rear_door_lock
                  name: Rear Door
                  show_state: true
                  aspect_ratio: 1/1
                  card_size: 3
                  size: 25%
                  tap_action:
                    action: call-service
                    service: |
                      [[[
                        if (states['lock.rear_door_lock'].state == "locked")
                          return "lock.unlock";
                        return "lock.lock";
                      ]]]
                    service_data:
                      entity_id: lock.rear_door_lock
                  styles:
                    icon:
                      - left: 15px
                      - top: '-25px'
                      - color: |
                          [[[
                            if (states['lock.rear_door_lock'].state == "unlocked")
                              return "rgba(230, 0, 0,0.7)";
                            return "white";
                          ]]]
                    card:
                      - background: |
                          [[[
                            if (states['lock.rear_door_lock'].state == "locked") 
                              return "rgba(255,255,255,0.1)";
                            return "rgba(255,255,255,0.7)";
                          ]]]
                      - border-radius: 12px
                      - box-shadow: 5px 5px 5px;
                      - font-size: 100%
                    grid:
                      - grid-template-areas: '"i" "n" "s"'
                      - grid-template-columns: 1fr
                      - grid-template-rows: 1fr min-content min-content
                    img_cell:
                      - align-self: start
                      - text-align: start
                    name:
                      - justify-self: start
                      - padding-left: 10px
                      - margin-top: '-65px'
                      - color: |
                          [[[
                            if (states['lock.rear_door_lock'].state == "unlocked")
                              return "black";
                            return "white";
                          ]]]
                    state:
                      - justify-self: start
                      - padding-left: 10px
                      - margin-top: '-32px'
                      - color: |
                          [[[
                            if (states['lock.rear_door_lock'].state == "unlocked")
                              return "black";
                            return "white";
                          ]]]
              square: true
          - type: markdown
            content: '### Alarm Trigger Sensors'
            card_mod:
              style: |
                ha-card {
                  background: rgba(0,0,0,0);
                  box-shadow: none;
                  padding: 0px;
                  margin-bottom: -12px;
                  left: 5px;
                }
          - type: entities
            entities:
              - entity: binary_sensor.entry_front
              - entity: binary_sensor.entry_garage
              - entity: binary_sensor.entry_rear
              - entity: binary_sensor.motion_family_rm
              - entity: binary_sensor.slider_front_rm
              - entity: binary_sensor.slider_master
              - entity: binary_sensor.slider_family_rm
              - entity: binary_sensor.slider_lanai
              - entity: binary_sensor.window_office
              - entity: binary_sensor.window_master_bath
              - entity: binary_sensor.window_laundry
              - entity: binary_sensor.window_josh
              - entity: binary_sensor.window_cruz
            state_color: false
            card_mod:
              style: |
                ha-card {
                  width: 92%;
                  margin: auto;
                  border-radius: 12px;
                  background: rgba(255,255,255,0.1);
                  color: white;
                  --paper-item-icon-color: white;
                }
          - type: markdown
            content: '### Occupancy Sensors'
            card_mod:
              style: |
                ha-card {
                  background: rgba(0,0,0,0);
                  box-shadow: none;
                  padding: 0px;
                  margin-bottom: -12px;
                  left: 5px;
                }
          - type: entities
            entities:
              - entity: binary_sensor.front_living_room
              - entity: binary_sensor.office
              - entity: binary_sensor.master
              - entity: binary_sensor.kitchen
              - entity: binary_sensor.family_room
              - entity: binary_sensor.josh
              - entity: binary_sensor.cruz
              - entity: binary_sensor.upstairs_2
                name: Ariel
                icon: 'mdi:walk'
            state_color: false
            card_mod:
              style: |
                ha-card {
                  width: 92%;
                  margin: auto;
                  border-radius: 12px;
                  background: rgba(255,255,255,0.1);
                  color: white;
                  --paper-item-icon-color: white;
                  margin-bottom: 15px;
                }
title: Security
